version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: deviceshop
      MYSQL_USER: suttyread
      MYSQL_PASSWORD: suttyread
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  deviceshop:
    image: deviceshop
    build: deviceshop
    restart: always
    depends_on:
      - db
    ports:
      - '9000:9000'
    expose:
      - '9000'