version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: deviceshop
      MYSQL_USER: suttyread
      MYSQL_PASSWORD: suttyread
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306